# Generated by Django 5.2 on 2025-05-07 15:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_deadlinetype_client_clientdocument_clientdeadline_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="deadlinetype",
            name="default_priority",
        ),
    ]
