# Generated by Django 5.2 on 2025-05-12 10:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_alter_user_options_user_role"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="clientdeadline",
            options={
                "ordering": ["due_date", "-priority"],
                "verbose_name": "Client Deadline",
                "verbose_name_plural": "Client Deadlines",
            },
        ),
        migrations.AlterModelOptions(
            name="user",
            options={
                "ordering": ["role", "first_name"],
                "verbose_name": "User",
                "verbose_name_plural": "Users",
            },
        ),
        migrations.AddField(
            model_name="clientdocument",
            name="deadline",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="documents",
                to="core.clientdeadline",
            ),
        ),
        migrations.AlterField(
            model_name="clientdeadline",
            name="deadline_type",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.RESTRICT, to="core.deadlinetype"
            ),
        ),
        migrations.AlterField(
            model_name="clientdocument",
            name="client",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="documents",
                to="core.client",
            ),
        ),
        migrations.AlterField(
            model_name="clientdocument",
            name="uploaded_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="documents_uploaded",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
