# Generated by Django 5.2 on 2025-05-17 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0007_notification"),
    ]

    operations = [
        migrations.AddField(
            model_name="notification",
            name="title",
            field=models.CharField(default="Test", max_length=255),
            preserve_default=False,
        ),
    ]
