# Generated by Django 5.2 on 2025-05-17 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0008_notification_title"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notification",
            name="link",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
