# Generated by Django 5.2 on 2025-05-24 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0009_alter_notification_link"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="clientdeadline",
            options={
                "ordering": [
                    models.Case(
                        models.When(status="in_progress", then=models.Value(0)),
                        models.When(status="pending", then=models.Value(1)),
                        models.When(status="overdue", then=models.Value(2)),
                        models.When(status="completed", then=models.Value(3)),
                        models.When(status="cancelled", then=models.Value(4)),
                        default=models.Value(5),
                    ),
                    "due_date",
                    "-priority",
                ],
                "verbose_name": "Client Deadline",
                "verbose_name_plural": "Client Deadlines",
            },
        ),
        migrations.AlterField(
            model_name="clientdeadline",
            name="priority",
            field=models.PositiveSmallIntegerField(
                choices=[
                    (5, "Highest"),
                    (4, "High"),
                    (3, "Medium"),
                    (2, "Low"),
                    (1, "Lowest"),
                ],
                default=3,
            ),
        ),
        migrations.AlterField(
            model_name="clientdeadline",
            name="status",
            field=models.CharField(
                choices=[
                    ("in_progress", "In Progress"),
                    ("pending", "Pending"),
                    ("overdue", "Overdue"),
                    ("completed", "Completed"),
                    ("cancelled", "Cancelled"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="workupdate",
            name="status",
            field=models.CharField(
                choices=[
                    ("in_progress", "In Progress"),
                    ("pending", "Pending"),
                    ("overdue", "Overdue"),
                    ("completed", "Completed"),
                    ("cancelled", "Cancelled"),
                ],
                max_length=20,
            ),
        ),
    ]
