# Generated by Django 5.2 on 2025-06-25 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0010_alter_clientdeadline_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="client",
            name="date_of_birth",
            field=models.DateField(blank=True, null=True),
        ),
    ]
