# Generated by Django 5.2 on 2025-08-18 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0011_client_date_of_birth"),
    ]

    operations = [
        migrations.AddField(
            model_name="client",
            name="category",
            field=models.CharField(
                blank=True,
                choices=[
                    ("TOE", "Tax (One Engagement)"),
                    ("TRP", "Tax (Regular Processing)"),
                    ("CMP", "Compliance"),
                    ("ACC", "Accounting"),
                    ("AUD", "Auditing"),
                    ("OCC", "Other Consultancy Client"),
                ],
                default="OCC",
                max_length=10,
            ),
        ),
    ]
