# Generated by Django 5.2 on 2025-08-26 04:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0011_client_date_of_birth"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="clientdeadline",
            name="assigned_to",
        ),
        migrations.RemoveField(
            model_name="clientdeadline",
            name="client",
        ),
        migrations.RemoveField(
            model_name="clientdeadline",
            name="created_by",
        ),
        migrations.RemoveField(
            model_name="clientdeadline",
            name="deadline_type",
        ),
        migrations.RemoveField(
            model_name="clientdocument",
            name="deadline",
        ),
        migrations.RemoveField(
            model_name="workupdate",
            name="deadline",
        ),
        migrations.RemoveField(
            model_name="clientdocument",
            name="client",
        ),
        migrations.RemoveField(
            model_name="clientdocument",
            name="uploaded_by",
        ),
        migrations.RemoveField(
            model_name="workupdate",
            name="created_by",
        ),
        migrations.AddField(
            model_name="client",
            name="tin",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.CreateModel(
            name="Task",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("compliance", "Compliance"),
                            ("financial_statement", "Financial Statement Preparation"),
                            ("accounting_audit", "Accounting Audit"),
                            ("finance_implementation", "Finance Implementation"),
                            ("hr_implementation", "Human Resource Implementation"),
                            ("miscellaneous", "Miscellaneous Tasks"),
                            ("tax_case", "Tax Case"),
                        ],
                        max_length=25,
                    ),
                ),
                ("description", models.CharField(max_length=255)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("completed", "Completed"),
                            ("for_revision", "For Revision"),
                            ("for_checking", "For Checking"),
                            ("on_going", "On Going"),
                            ("pending", "Pending"),
                            ("not_yet_started", "Not Yet Started"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="not_yet_started",
                        max_length=20,
                    ),
                ),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("high", "High"),
                            ("medium", "Medium"),
                            ("low", "Low"),
                        ],
                        default="medium",
                        max_length=6,
                    ),
                ),
                ("deadline", models.DateField()),
                ("remarks", models.TextField(blank=True, null=True)),
                ("date_complied", models.DateField(blank=True, null=True)),
                ("completion_date", models.DateField(blank=True, null=True)),
                ("last_update", models.DateTimeField(blank=True, null=True)),
                ("status_history", models.JSONField(blank=True, default=list)),
                (
                    "period_covered",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("engagement_date", models.DateField(blank=True, null=True)),
                ("steps", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "requirements",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("type", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "needed_data",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("area", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "tax_category",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("OTE", "One-Time Engagement"),
                            ("RP", "Regular Process"),
                        ],
                        max_length=3,
                        null=True,
                    ),
                ),
                (
                    "tax_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("PT", "Percentage Tax"),
                            ("IT", "Income Tax"),
                            ("WE", "Withholding Tax - Expanded"),
                        ],
                        max_length=2,
                        null=True,
                    ),
                ),
                (
                    "form",
                    models.CharField(
                        blank=True,
                        choices=[
                            (
                                "2551Q",
                                "BIR Form 2551Q - Quarterly Percentage Tax Return",
                            ),
                            (
                                "1701",
                                "BIR Form 1701 - Annual Income Tax Return (Individuals, Estates, Trusts)",
                            ),
                            (
                                "0619E",
                                "BIR Form 0619E - Monthly Remittance Form of Creditable Income Taxes Withheld (Expanded)",
                            ),
                            (
                                "1601EQ",
                                "BIR Form 1601-EQ - Quarterly Remittance Return of Creditable Income Taxes Withheld (Expanded)",
                            ),
                        ],
                        max_length=6,
                        null=True,
                    ),
                ),
                (
                    "working_paper",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "tax_payable",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                ("last_followup", models.DateField(blank=True, null=True)),
                (
                    "assigned_to",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="tasks_assigned_to",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT, to="core.client"
                    ),
                ),
            ],
            options={
                "db_table": "tasks",
            },
        ),
        migrations.DeleteModel(
            name="DeadlineType",
        ),
        migrations.DeleteModel(
            name="ClientDeadline",
        ),
        migrations.DeleteModel(
            name="ClientDocument",
        ),
        migrations.DeleteModel(
            name="WorkUpdate",
        ),
        migrations.AddIndex(
            model_name="task",
            index=models.Index(
                fields=["category", "status"], name="tasks_categor_c91700_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="task",
            index=models.Index(
                fields=["assigned_to", "deadline"], name="tasks_assigne_a5d071_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="task",
            index=models.Index(
                fields=["client", "category"], name="tasks_client__8e3598_idx"
            ),
        ),
    ]
