# Generated by Django 5.2 on 2025-08-26 06:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0012_remove_clientdeadline_assigned_to_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="task",
            name="status_history",
        ),
        migrations.AddField(
            model_name="task",
            name="current_approval_step",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="task",
            name="requires_approval",
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name="TaskApproval",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("approved", "Approved"),
                            ("rejected", "Rejected/For Revision"),
                            ("pending", "Pending Review"),
                        ],
                        default="pending",
                        max_length=10,
                    ),
                ),
                ("comments", models.TextField(blank=True, null=True)),
                ("step_number", models.PositiveIntegerField(default=1)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "approver",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="task_approvals_given",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "next_approver",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="pending_approvals",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "task",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="approvals",
                        to="core.task",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="TaskStatusHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "old_status",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("completed", "Completed"),
                            ("for_revision", "For Revision"),
                            ("for_checking", "For Checking"),
                            ("on_going", "On Going"),
                            ("pending", "Pending"),
                            ("not_yet_started", "Not Yet Started"),
                            ("cancelled", "Cancelled"),
                        ],
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "new_status",
                    models.CharField(
                        choices=[
                            ("completed", "Completed"),
                            ("for_revision", "For Revision"),
                            ("for_checking", "For Checking"),
                            ("on_going", "On Going"),
                            ("pending", "Pending"),
                            ("not_yet_started", "Not Yet Started"),
                            ("cancelled", "Cancelled"),
                        ],
                        max_length=20,
                    ),
                ),
                ("remarks", models.TextField(blank=True, null=True)),
                (
                    "change_type",
                    models.CharField(
                        choices=[
                            ("manual", "Manual Update"),
                            ("approval", "Approval Process"),
                            ("system", "System Update"),
                        ],
                        default="manual",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "changed_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="status_changes_made",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "related_approval",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="status_changes",
                        to="core.taskapproval",
                    ),
                ),
                (
                    "task",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="status_history_records",
                        to="core.task",
                    ),
                ),
            ],
            options={
                "verbose_name": "Task Status History",
                "verbose_name_plural": "Task Status Histories",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="taskapproval",
            index=models.Index(
                fields=["task", "step_number"], name="core_taskap_task_id_58f6c4_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="taskapproval",
            index=models.Index(
                fields=["approver", "action"], name="core_taskap_approve_5403d0_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="taskapproval",
            unique_together={("task", "approver", "step_number")},
        ),
        migrations.AddIndex(
            model_name="taskstatushistory",
            index=models.Index(
                fields=["task", "-created_at"], name="core_taskst_task_id_eb5285_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="taskstatushistory",
            index=models.Index(
                fields=["changed_by", "-created_at"],
                name="core_taskst_changed_a90e6c_idx",
            ),
        ),
    ]
