# Generated by Django 5.2 on 2025-08-23 03:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0012_compliance"),
    ]

    operations = [
        migrations.CreateModel(
            name="FinancialStatementPreparation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("type", models.CharField(max_length=255)),
                ("needed_data", models.CharField(max_length=255)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("completed", "Completed"),
                            ("for_revision", "For Revision"),
                            ("for_checking", "For Checking"),
                            ("on_going", "On Going"),
                            ("pending", "Pending"),
                            ("not_yet_started", "Not Yet Started"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="not_yet_started",
                        max_length=20,
                    ),
                ),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("high", "High"),
                            ("medium", "Medium"),
                            ("low", "Low"),
                        ],
                        default="medium",
                        max_length=6,
                    ),
                ),
                ("deadline", models.DateField()),
                ("remarks", models.TextField(blank=True, null=True)),
                ("date_complied", models.DateField(blank=True, null=True)),
                ("completion_date", models.DateField(blank=True, null=True)),
                ("last_update", models.DateTimeField(blank=True, null=True)),
                (
                    "assigned_to",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT, to="core.client"
                    ),
                ),
            ],
        ),
    ]
