# Generated by Django 5.2 on 2025-08-30 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0014_clientdocument"),
    ]

    operations = [
        migrations.AddField(
            model_name="clientdocument",
            name="deleted_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="clientdocument",
            name="is_deleted",
            field=models.BooleanField(default=False),
        ),
    ]
