# Generated by Django 5.2 on 2025-09-04 03:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0015_add_soft_delete_fields"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="clientdocument",
            name="deleted_at",
        ),
        migrations.RemoveField(
            model_name="clientdocument",
            name="is_deleted",
        ),
    ]
