# Generated by Django 5.2 on 2025-08-24 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0016_miscellaneoustasks"),
    ]

    operations = [
        migrations.AddField(
            model_name="client",
            name="tin",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
