# Generated by Django 5.2 on 2025-08-24 06:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0017_client_tin"),
    ]

    operations = [
        migrations.CreateModel(
            name="TaxCase",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("OTE", "One-Time Engagement"),
                            ("RP", "Regular Process"),
                        ],
                        default=None,
                        max_length=3,
                        null=True,
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("PT", "Percentage Tax"),
                            ("IT", "Income Tax"),
                            ("WE", "Withholding Tax - Expanded"),
                        ],
                        default=None,
                        max_length=2,
                        null=True,
                    ),
                ),
                (
                    "form",
                    models.CharField(
                        blank=True,
                        choices=[
                            (
                                "2551Q",
                                "BIR Form 2551Q - Quarterly Percentage Tax Return",
                            ),
                            (
                                "1701",
                                "BIR Form 1701 - Annual Income Tax Return (Individuals, Estates, Trusts)",
                            ),
                            (
                                "0619E",
                                "BIR Form 0619E - Monthly Remittance Form of Creditable Income Taxes Withheld (Expanded)",
                            ),
                            (
                                "1601EQ",
                                "BIR Form 1601-EQ - Quarterly Remittance Return of Creditable Income Taxes Withheld (Expanded)",
                            ),
                        ],
                        default=None,
                        max_length=6,
                        null=True,
                    ),
                ),
                ("period_covered", models.CharField(max_length=255)),
                ("working_paper", models.CharField(max_length=255)),
                (
                    "tax_payable",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
                ),
                ("last_followup", models.DateField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("completed", "Completed"),
                            ("for_revision", "For Revision"),
                            ("for_checking", "For Checking"),
                            ("on_going", "On Going"),
                            ("pending", "Pending"),
                            ("not_yet_started", "Not Yet Started"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="not_yet_started",
                        max_length=20,
                    ),
                ),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("high", "High"),
                            ("medium", "Medium"),
                            ("low", "Low"),
                        ],
                        default="medium",
                        max_length=6,
                    ),
                ),
                ("engagement_date", models.DateField()),
                ("deadline", models.DateField()),
                ("remarks", models.TextField(blank=True, null=True)),
                ("date_complied", models.DateField(blank=True, null=True)),
                ("completion_date", models.DateField(blank=True, null=True)),
                ("last_update", models.DateTimeField(blank=True, null=True)),
                (
                    "assigned_to",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT, to="core.client"
                    ),
                ),
            ],
        ),
    ]
