# Generated by Django 5.2 on 2025-08-24 11:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0018_taxcase"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="clientdeadline",
            name="assigned_to",
        ),
        migrations.RemoveField(
            model_name="clientdeadline",
            name="client",
        ),
        migrations.RemoveField(
            model_name="clientdeadline",
            name="created_by",
        ),
        migrations.RemoveField(
            model_name="clientdeadline",
            name="deadline_type",
        ),
        migrations.RemoveField(
            model_name="clientdocument",
            name="deadline",
        ),
        migrations.RemoveField(
            model_name="workupdate",
            name="deadline",
        ),
        migrations.RemoveField(
            model_name="clientdocument",
            name="client",
        ),
        migrations.RemoveField(
            model_name="clientdocument",
            name="uploaded_by",
        ),
        migrations.RemoveField(
            model_name="workupdate",
            name="created_by",
        ),
        migrations.DeleteModel(
            name="DeadlineType",
        ),
        migrations.DeleteModel(
            name="ClientDeadline",
        ),
        migrations.DeleteModel(
            name="ClientDocument",
        ),
        migrations.DeleteModel(
            name="WorkUpdate",
        ),
    ]
