# Generated by Django 5.2 on 2025-08-24 12:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0019_remove_clientdeadline_assigned_to_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="accountingaudit",
            name="assigned_to",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="accounting_audits_assigned_to",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="compliance",
            name="assigned_to",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="compliances_assigned_to",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="financeimplementation",
            name="assigned_to",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="finance_implementations_assigned_to",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="financialstatementpreparation",
            name="assigned_to",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="financial_statement_preparations_assigned_to",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="humanresourceimplementation",
            name="assigned_to",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="human_resource_implementations_assigned_to",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="miscellaneoustasks",
            name="assigned_to",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="miscellaneous_tasks_assigned_to",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="taxcase",
            name="assigned_to",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="tax_cases_assigned_to",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
