# Generated by Django 5.2 on 2025-08-25 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0020_alter_accountingaudit_assigned_to_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="taxcase",
            name="status_history",
            field=models.JSONField(blank=True, default=list),
        ),
    ]
