# Generated by Django 5.2 on 2025-08-25 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0021_taxcase_status_history"),
    ]

    operations = [
        migrations.AddField(
            model_name="accountingaudit",
            name="status_history",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="compliance",
            name="status_history",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="financeimplementation",
            name="status_history",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="financialstatementpreparation",
            name="status_history",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="humanresourceimplementation",
            name="status_history",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="miscellaneoustasks",
            name="status_history",
            field=models.JSONField(blank=True, default=list),
        ),
    ]
